export const COMPLETIONS = [
  `{app="nginx"}`,
  `|= "error"`,
  `!= "healthcheck"`,
  `|~ "err|warn"`,
  `!~ "timeout"`,
  `| json`,
  `| logfmt`,
  `| regexp "(?P<level>info|warn|error)"`,
  `| pattern "<_> <level> <msg>"`,
  `| line_format "{{._msg}}"`,
  `| label_format level="{{.level}}"`,
  `| drop pod, container`,
  `| keep app, host`,
  `rate({app="nginx"}[5m])`,
  `count_over_time({app="nginx"}[5m])`,
  `sum(rate({app="nginx"}[5m]))`,
  `topk(5, sum by (status) (rate({app="nginx"}[5m])))`,
];
